project_name: dotnet-appsettings-env

builds:
  - id: default
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - format: zip
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git

release:
  github:
    name_template: "v{{ .Version }}"
